name: "Print action version to console"
description: "Prints this Action's Version number to console."
branding:
  icon: "check-circle"
  color: "gray-dark"
inputs:
  input-example:
    description: "This is a placeholder for an input. It will print to console too."
    default: "Default Input Text"
  github-token:
    description: "Github token used for including the skylink url in pull request"
    required: true
outputs:
  version:
    description: "What we will tag and release this version as."
runs:
  using: "node12"
  main: index.js
